# Generated by Django 4.2.11 on 2024-04-23 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='recipe',
        ),
    ]
